apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wasmmodules.volgenic.com
spec:
  group: volgenic.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                path:
                  type: string
                contents:
                  type: string
  scope: Namespaced
  names:
    plural: wasmmodules
    singular: wasmmodule
    kind: WasmModule
    shortNames:
      - wm
